sudo: required


services: 
 - docker


env:
  - DOCKER_COMPOSE_VERSION: 1.8.0


before_install:
  - sudo apt-get update
#  - sudo apt-get -y -q -o Dpkg::Options::="--force-confnew" install docker-engine

  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
#  - cd /django/docker
  - docker-compose up --build -d
#  - docker-compose up -d mysql_test
#  - docker-compose run workspace composer install
#  - cp .env.example .env
#  - docker-compose run workspace php artisan key:generate

  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

before_script:
   - touch django/src/.env
   - echo HOSTENV=$HOSTENV >> django/src/.env
   - echo DEBUG=$DJANGO_DEBUG >> django/src/.env
   - echo SECRET_KEY=$DJANGO_SECRET_KEY >> django/src/.env
   - echo DATABASE_ENGINE=$DJANGO_DATABASE_ENGINE >> django/src/.env
   - echo DATABASE_DB=$DJANGO_DATABASE_DB >> django/src/.env
   - echo DATABASE_USER=$DJANGO_DATABASE_USER >> django/src/.env
   - echo DATABASE_PASSWORD=$DJANGO_DATABASE_PASSWORD >> django/src/.env
   - echo DATABASE_HOST=$DJANGO_DATABASE_HOST >> django/src/.env
   - echo DATABASE_PORT=$DJANGO_DATABASE_PORT >> django/src/.env
   - echo DATABASE=$DJANGO_DATABASE >> django/src/.env
#   - psql -c 'create database travis_ci_test;' -U postgres


script:
#  - docker-compose exec django1 python3 manage.py makemigrations boardapp
  - docker-compose exec django1 bash -c "python3 manage.py migrate"
#  - docker-compose exec django1 python3 manage.py createsuperuser
#  - docker-compose exec django1 python3 manage.py runserver 0.0.0.0:8000
  - docker-compose exec django1 python3 manage.py test


deploy:
  provider: script
  script:
   - docker build -t registry heroku.com/$HEROKU_APP_NAME/web -f django/docker/dockerfile.prod .;
   - docker push registry heroku.com/$HEROKU_APP_NAME/web;
   - heroku run --app $HEROKU_APP_NAME python3 manage.py migrate;
  on:
    branch: master

