# pull ubuntu Image #####
FROM ubuntu:latest


# install python #####
RUN apt-get update && apt-get install -y sudo     # update installable lib. list (not install)
                                                  # install sudo package
# RUN  apt-get -y upgrade                         # upgrate already install package 
RUN  apt-get install -y locales curl python3-distutils
                                                  # install locales and transfer pip lib
RUN apt -y install libpq-dev                      # required pg_config to build psycopg2 from source

# install python library #####
RUN  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
                                                  # transfer get-pip.py to local 
RUN  python3 get-pip.py                           # install pip lib (exe get-pip.py)
RUN  pip install -U pip
RUN  python3 -m pip install --upgrade pip        # upgrate pip to latest


# locales setting #####
RUN  mkdir /var/django
RUN  rm -rf /var/lib/apt/lists/*
RUN  localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8


# django setting #####
WORKDIR /var/django
ADD docker/req.txt /var/django
RUN pip install -r req.txt    # pylib install from req.txt

