version: '3'

services:
    django:
      build:
        context: ../
        dockerfile: ./docker/dockerfile.env
      ports:
        - '8123:8000'
      volumes:
        - '../src:/var/django'
      container_name: my-django
      tty: true
      stdin_open: true
